import { MembershipPlan, Trainer, GymClass, Testimonial, BlogPost, GalleryItem, ClassBooking, BillingHistoryItem } from "@/types";

export const membershipPlans: MembershipPlan[] = [
  {
    id: "plan-starter",
    name: "STARTER",
    slug: "starter",
    monthlyPrice: 999,
    annualPrice: 799,
    category: "BASIC ACCESS",
    isPopular: false,
    features: [
      "Access to Cardio Zone",
      "Standard Strength Area",
      "Locker Room Access",
      "No Guest Passes",
    ],
  },
  {
    id: "plan-pro",
    name: "PRO",
    slug: "pro",
    monthlyPrice: 1799,
    annualPrice: 1439,
    category: "FULL EXPERIENCE",
    isPopular: true,
    features: [
      "All Standard Features",
      "Unlimited Group Classes",
      "Premium Sauna Access",
      "2 Guest Passes / Mo",
    ],
  },
  {
    id: "plan-elite",
    name: "ELITE",
    slug: "elite",
    monthlyPrice: 2999,
    annualPrice: 2399,
    category: "VIP STATUS",
    isPopular: false,
    features: [
      "All Pro Features",
      "Private Locker & Laundry",
      "Weekly Nutrition Consult",
      "Priority Booking Access",
    ],
  },
];

export const trainers: Trainer[] = [
  {
    id: "trainer-marcus",
    name: "MARCUS VANCE",
    slug: "marcus-vance",
    specialization: ["STRENGTH & CONDITIONING"],
    bio: "Elite level powerlifting coach with 12+ years experience in professional sports performance.",
    longBio: "Marcus Vance is more than a coach; he is a specialist in the science of human performance. With a background in collegiate athletics and a Master's in Exercise Physiology, Marcus has dedicated over a decade to refining the training protocols used by professional powerlifters and executive athletes alike. His methodology combines brutal foundational strength work with modern data-driven recovery.",
    experience: 12,
    certifications: [
      "NSCA Certified Strength & Conditioning Specialist",
      "NASM Performance Enhancement Specialist",
      "Precision Nutrition L2",
      "Westside Barbell Certified",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsjiYXVk4_c4TMuJm4SffWthpskERIzWG_fu4gy5N_8pBSeYE27wQ8Pii1Vv3gkhJnBxguKyie5t5c1yvxUNFP7PyHYQPl4QP9aCHhVHDYlajcwaWItcHe1DJx1jBQyRPKu8nHMw2IXKX-aHwb1BhSs5i9Oh28JJKXtS8M91INR660_331PELqZIdGr1GwKRMw3f_Vrzjeb9R8huS38Lt8CEqgkrCLz9oZWQBSFxMOeHVAelWPy1Aaik6QmJjkxHXKZd0Cy9ZY9Vns",
    instagramUrl: "https://instagram.com/marcusvance",
    rating: 4.9,
    isFeatured: true,
    quote: "Strength is the foundation of every human endeavor.",
    schedule: [
      { days: "MON-WED", hours: "06:00 - 12:00" },
      { days: "THU-FRI", hours: "14:00 - 20:00" },
      { days: "SATURDAY", hours: "08:00 - 14:00" },
      { days: "SUNDAY", hours: "CLOSED" },
    ],
  },
  {
    id: "trainer-elara",
    name: "ELARA JENKINS",
    slug: "elara-jenkins",
    specialization: ["HYPERTROPHY SPECIALIST"],
    bio: "IFBB Pro specializing in body composition transformation and metabolic health optimization.",
    longBio: "Elara Jenkins combines the discipline of IFBB pro bodybuilders with modern physiological science. She specializes in body transformations, muscular symmetry, and hormonal health management, guiding high-profile executives and competitors to peak physical structure.",
    experience: 9,
    certifications: [
      "IFBB Pro Card Holder",
      "ACE Certified Personal Trainer",
      "FMS Level 2 Specialist",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEkr3yICD7yBDvTNxGklbCum24uXa-Ur1sFqkn2LCsEpWHtBF2971eLTece4mKZgCQkzPk7sscPhJgecYOJcMJsDRbF3nZR_fQNWHZbtWqS6ILWv-KU7e3ojTwB51myzoWxe7etSavDMznzgpMuNWCBzGMgVc-peHgz-870B4bww2l6vlDvJcVOJXHH0OgMVBWyFJeh5KNLDkjpn0czoSh6LuWpjOaOpOvo-P2p6ZH3Wb0N6H2bmLROIybWGjNJoGKY2sC7aj9MKur",
    instagramUrl: "https://instagram.com/elarajenkins",
    rating: 4.8,
  },
  {
    id: "trainer-david",
    name: "DR. DAVID CHOW",
    slug: "david-chow",
    specialization: ["COMBAT PERFORMANCE"],
    bio: "Former professional fighter and PhD in Sports Biomechanics focused on explosive power.",
    longBio: "Dr. David Chow applies advanced biomechanics to elite combat sports. A former MMA champion, David conducts metabolic analysis and mechanical optimizations to develop explosive power, speed, and structural integrity for ring and cage fighters.",
    experience: 15,
    certifications: [
      "PhD in Sports Biomechanics",
      "CSCS *D (Distinction)",
      "USA Weightlifting Coach L2",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDu90Ol4rXkzvvGsvVmOVNnN_AQ-wIVfXsTv_J3Yk9Bctpjxyy8ucNSOuxDyvRCwuh1QmNnBxsAcUFVURw7d0NcwZtCciflIeYz67ijcdk2i2A5Tht0Tp4AeQ30JiHHLacH3JGn7Pc7XdIRnCyszsvEX3jgPcuhp-oBK8GRMylrtrxoaQXy01u4zNYxiyURxDz074jhNQGLhMqXbnII4WuIDBbuE86jbHETNyFFMSzqRUDoD7jiiyQv4tUBawk6b1ZVCZkUdQ_gh8Cr",
    instagramUrl: "https://instagram.com/drdavidchow",
    rating: 5.0,
  },
  {
    id: "trainer-sarah",
    name: "SARAH NIGHTINGALE",
    slug: "sarah-nightingale",
    specialization: ["MOBILITY & RECOVERY"],
    bio: "Expert in restorative movement and elite-level recovery protocols for high-volume athletes.",
    longBio: "Sarah Nightingale focuses on joint health, physical longevity, and athletic recovery. She works closely with power athletes to release tension, correct imbalances, and enhance core mobility through targeted restorative workflows.",
    experience: 8,
    certifications: [
      "Registered Yoga Teacher (RYT-500)",
      "Corrective Exercise Specialist (CES)",
      "Dynamic Neuromuscular Stabilization (DNS) Practitioner",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC5X4OLeaz9WDNeMCT4F8e4XDKD2T_DwB8ryVowkJXOoeFBMtGDFSCQxaw1Ep2ilwAAHoaVIVhYcq8-8CpdzUy49ySiN2sSBaOuFt7hVL1KKluMrgn6XSqIoBz-Hhs0yuHdjxD37yX8UeUXF5ZzY8VsdvSxRxiok8bm8Xo0NMChOH4ramHdGb8AP6C80bB-Kc4ylvH-ArH3cNsEeevhIsix21j8WTL1dUH9Aq3wmIsvvGVwW0Rad6MExHawyLaaTv85v9hgvXOg-WKe",
    rating: 4.7,
  },
  {
    id: "trainer-jaxson",
    name: "JAXSON REED",
    slug: "jaxson-reed",
    specialization: ["FUNCTIONAL INTENSITY"],
    bio: "Specializing in metabolic conditioning and brutal functional hypertrophy blocks.",
    longBio: "Jaxson Reed trains athletes like machines. His functional intensity programs combine strongman carry patterns, aerobic threshold building, and raw structural conditioning blocks to push members past their limits.",
    experience: 7,
    certifications: [
      "CrossFit Level 3 Trainer",
      "NASM Performance Enhancement Specialist",
      "IKFF Kettlebell Master Trainer",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA-ESeVWwa3kYWi58hnSPxbgKBO_ShArKZHkxjsDUZqP5LraPnvj46IciA3HMCA5T1jtwNgqF7Dz6K76UKr-fFehGRSlBWOTNWLW9KbT8aNqKrnj1tJbSMbTPSC31e0ZvbDlDOdwgbgZaIJZIxip_60DP-mSl4fvOtaWGe3Kzn2NB-OAqtRqnjQUkxO2EthRpnE8t8yfOSIKZuKO9RhkFl6BzBxrTB_xLaDiH-ZGsYlN4dotZ-1cJh16eE9GIYClf7DnOiJZmzEvguV",
    rating: 4.8,
  },
  {
    id: "trainer-sofia",
    name: "SOFIA VALENTINE",
    slug: "sofia-valentine",
    specialization: ["MASTER TRAINER"],
    bio: "Founder of the IronForge Method. 15 years leading transformation for elite clientele.",
    longBio: "Sofia Valentine is the visionary founder behind IronForge's athletic standards. Over 15 years, she has crafted training systems for professional models, Olympic athletes, and high-performance teams, merging raw power with editorial luxury aesthetics.",
    experience: 15,
    certifications: [
      "Master Trainer (EHFA)",
      "BSc in Exercise Science",
      "Poliquin Strength Coach L3",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBIr9Rw2wtCwtDT9p9INkogrClVrSgzBAygac1zCu-zCrmUZbvMDByRkbrWGaVwy_UsHwySOq03MtU8AnuGlzwrQCTwWhj9_eXEBHB71irrsGwNauTngJW7hwFX6R4p3ITpn6SQOfZueYum_9SeTWiBo5al1J8eFp05fGuVElGoWGNXIlDLMvCvQupWt-K96v0pDP-E1vFfxgDoWPqbC_zdlE5k0CuDg1NeZOPa-CPmArDDBqJo1UHpgE4dUIA2OENR6DFwYugfsQ4W",
    rating: 5.0,
    isFeatured: true,
  },
];

export const gymClasses: GymClass[] = [
  {
    id: "class-crossfit",
    name: "ELITE CROSSFIT AMRAP",
    slug: "elite-crossfit-amrap",
    description: "Master technical movements and push your aerobic capacity with our flagship high-intensity conditioning class.",
    type: "CROSSFIT",
    trainerId: "trainer-jaxson",
    trainerName: "Coach Jaxson",
    dayOfWeek: 1, // Mon
    startTime: "07:00",
    duration: 60,
    capacity: 20,
    slotsLeft: 5,
    isFeatured: true,
  },
  {
    id: "class-hiit-mon",
    name: "POWER HIIT",
    slug: "power-hiit",
    description: "High-intensity interval conditioning designed to boost cardiorespiratory threshold.",
    type: "HIIT",
    trainerId: "trainer-sarah",
    trainerName: "Coach Sarah",
    dayOfWeek: 1, // Mon
    startTime: "06:00",
    duration: 45,
    capacity: 15,
    slotsLeft: 4,
  },
  {
    id: "class-yoga-mon",
    name: "FLOW YOGA",
    slug: "flow-yoga",
    description: "Vinyasa yoga flow for movement integration and deep recovery.",
    type: "YOGA",
    trainerId: "trainer-sarah",
    trainerName: "Coach Sarah",
    dayOfWeek: 1, // Mon
    startTime: "08:30",
    duration: 60,
    capacity: 15,
    slotsLeft: 0,
  },
  {
    id: "class-strength-mon",
    name: "STRENGTH LAB",
    slug: "strength-lab",
    description: "Raw strength training focus using compound movements and barbell blocks.",
    type: "STRENGTH",
    trainerId: "trainer-marcus",
    trainerName: "Coach Marcus",
    dayOfWeek: 1, // Mon
    startTime: "17:00",
    duration: 60,
    capacity: 12,
    slotsLeft: 12,
  },
  {
    id: "class-core-tue",
    name: "CORE BLAST",
    slug: "core-blast",
    description: "Core stability, trunk strength, and functional bracing focus.",
    type: "STRENGTH",
    trainerId: "trainer-elara",
    trainerName: "Coach Elara",
    dayOfWeek: 2, // Tue
    startTime: "07:00",
    duration: 45,
    capacity: 15,
    slotsLeft: 2,
  },
  {
    id: "class-boxing-wed",
    name: "IRON BOXING",
    slug: "iron-boxing",
    description: "Heavy bag drill intervals and technical combat footwork protocols.",
    type: "BOXING",
    trainerId: "trainer-david",
    trainerName: "Coach David",
    dayOfWeek: 3, // Wed
    startTime: "06:00",
    duration: 60,
    capacity: 10,
    slotsLeft: 0,
  },
  {
    id: "class-yoga-thu",
    name: "ZEN FLOW",
    slug: "zen-flow",
    description: "Deep restorative mobility poses to prepare the body for peak load.",
    type: "YOGA",
    trainerId: "trainer-sarah",
    trainerName: "Coach Sarah",
    dayOfWeek: 4, // Thu
    startTime: "18:30",
    duration: 60,
    capacity: 15,
    slotsLeft: 8,
  },
  {
    id: "class-amrap-fri",
    name: "AMRAP ELITE",
    slug: "amrap-elite",
    description: "Brutal functional circuits focusing on metabolic output and raw endurance.",
    type: "CROSSFIT",
    trainerId: "trainer-jaxson",
    trainerName: "Coach Jaxson",
    dayOfWeek: 5, // Fri
    startTime: "06:00",
    duration: 60,
    capacity: 20,
    slotsLeft: 5,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Alexander Vance",
    role: "Executive Board Member",
    rating: 5,
    quote: "IronForge redefined my standard of performance. The atmosphere is intense, but the amenities and training precision are pure luxury.",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC5X4OLeaz9WDNeMCT4F8e4XDKD2T_DwB8ryVowkJXOoeFBMtGDFSCQxaw1Ep2ilwAAHoaVIVhYcq8-8CpdzUy49ySiN2sSBaOuFt7hVL1KKluMrgn6XSqIoBz-Hhs0yuHdjxD37yX8UeUXF5ZzY8VsdvSxRxiok8bm8Xo0NMChOH4ramHdGb8AP6C80bB-Kc4ylvH-ArH3cNsEeevhIsix21j8WTL1dUH9Aq3wmIsvvGVwW0Rad6MExHawyLaaTv85v9hgvXOg-WKe",
  },
  {
    id: "test-2",
    name: "Sarah Chen",
    role: "Competitive Triathlete",
    rating: 5,
    quote: "Having access to the recovery suite and physical therapy consultants has kept me injury-free for two straight competition blocks. Outstanding.",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBIr9Rw2wtCwtDT9p9INkogrClVrSgzBAygac1zCu-zCrmUZbvMDByRkbrWGaVwy_UsHwySOq03MtU8AnuGlzwrQCTwWhj9_eXEBHB71irrsGwNauTngJW7hwFX6R4p3ITpn6SQOfZueYum_9SeTWiBo5al1J8eFp05fGuVElGoWGNXIlDLMvCvQupWt-K96v0pDP-E1vFfxgDoWPqbC_zdlE5k0CuDg1NeZOPa-CPmArDDBqJo1UHpgE4dUIA2OENR6DFwYugfsQ4W",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "blog-1",
    title: "THE BIOMECHANICS OF THE compound Deadlift",
    slug: "biomechanics-deadlift",
    excerpt: "Breaking down joint load, neural fatigue, and muscular coordination for maximum structural output.",
    category: "TRAINING",
    readTime: "6 min read",
    publishedAt: "OCT 05, 2024",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7PV96otBPskyWgLMrT8T-tZenQxysbG9VGdRfA0rEFrzDR-YL4L4iQSewl2EU9nDzIzWFJUBhTufjoXCLO--uhrq2dVPcNVqxifmaGUmfyU33a0lsM_rtgoHcywE_YUR1DAuo8sn4gkB6cEHsDV7SNMjC47Pc20vutONObM1VXXhohTXVR7PP0ks-o-t81LRgarqVbSqj8KNN1X0y6rMjtmCua4djKXxMSNdk8g06v4onVqtxnlOsD1ypBTAotdsFPzkP8sbZk_FG",
    author: {
      name: "Marcus Vance",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsjiYXVk4_c4TMuJm4SffWthpskERIzWG_fu4gy5N_8pBSeYE27wQ8Pii1Vv3gkhJnBxguKyie5t5c1yvxUNFP7PyHYQPl4QP9aCHhVHDYlajcwaWItcHe1DJx1jBQyRPKu8nHMw2IXKX-aHwb1BhSs5i9Oh28JJKXtS8M91INR660_331PELqZIdGr1GwKRMw3f_Vrzjeb9R8huS38Lt8CEqgkrCLz9oZWQBSFxMOeHVAelWPy1Aaik6QmJjkxHXKZd0Cy9ZY9Vns",
    },
  },
  {
    id: "blog-2",
    title: "METABOLIC ADAPTATION IN CALORIC deficit",
    slug: "metabolic-adaptation-deficit",
    excerpt: "How thyroid activity and energy efficiency adjust during fat loss blocks—and how to offset stagnation.",
    category: "NUTRITION",
    readTime: "8 min read",
    publishedAt: "SEP 28, 2024",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxKZYzKOKQ9iNOCI79TLv6OdmgAWT7QeNNMsYJoI3ciV1UJunF1ivi2pfYlinXbtEKTOPRmwnCAFFQTUQEGA4lHfG4-qDvYAy787Lu-C5EHBCXqpto2b8zyF-D2TcFO-4t98y_HzeUGLriKoYTxqky_XD9ei5KbhbZybpMy3UxuXfSv9jP1NAhpBi3mn_fMcRvL0nWVGgtsdXnf27DLwOMLnZ0nX4CrFL5i97qaEuJqq07TNhU9apd83LSyM4smA_BhTG1ctW3Jtz5",
    author: {
      name: "Elara Jenkins",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEkr3yICD7yBDvTNxGklbCum24uXa-Ur1sFqkn2LCsEpWHtBF2971eLTece4mKZgCQkzPk7sscPhJgecYOJcMJsDRbF3nZR_fQNWHZbtWqS6ILWv-KU7e3ojTwB51myzoWxe7etSavDMznzgpMuNWCBzGMgVc-peHgz-870B4bww2l6vlDvJcVOJXHH0OgMVBWyFJeh5KNLDkjpn0czoSh6LuWpjOaOpOvo-P2p6ZH3Wb0N6H2bmLROIybWGjNJoGKY2sC7aj9MKur",
    },
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    title: "High Performance Strength Area",
    category: "EQUIPMENT",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7PV96otBPskyWgLMrT8T-tZenQxysbG9VGdRfA0rEFrzDR-YL4L4iQSewl2EU9nDzIzWFJUBhTufjoXCLO--uhrq2dVPcNVqxifmaGUmfyU33a0lsM_rtgoHcywE_YUR1DAuo8sn4gkB6cEHsDV7SNMjC47Pc20vutONObM1VXXhohTXVR7PP0ks-o-t81LRgarqVbSqj8KNN1X0y6rMjtmCua4djKXxMSNdk8g06v4onVqtxnlOsD1ypBTAotdsFPzkP8sbZk_FG",
    alt: "Moody high-contrast close-up of custom iron plates and olympic bars in industrial luxury gym settings.",
  },
  {
    id: "gal-2",
    title: "CrossFit Technical Session",
    category: "CLASSES",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8LuNheH21q5pKpQlxwaEvcDD24HmVRtGmoO6PSMWL8YMsJY_SHCvrxZun65RH63L4Mmq03gs4-B0mVv72qtxTjel-JmcpRnZT1CWjhqTC83u6i5ZjOHeYThZdM9gEkgfEqvSUr-5PZP3F3KBjiFEVdAHG0YKcfJufxgCWlmNemRpU_PpU5KPf0pS3Ew7JqqZwY0x2MeOrWL_b22uO0-4TJrLxFi7qIkXuM2QXYVV0O8jILrgKWdQ6cGBqdwTEa16XGES9-9gpLl_L",
    alt: "Gritty black and white image of crossfit members training explosive Olympic clean and jerks.",
  },
];

export const mockDashboardBookings: ClassBooking[] = [
  {
    id: "bk-1",
    classId: "class-strength-foundations",
    className: "POWER LIFTING: FOUNDATIONS",
    classDate: "OCT 14",
    startTime: "06:30 AM",
    trainerName: "Coach Marcus",
    status: "CONFIRMED",
  },
  {
    id: "bk-2",
    classId: "class-hiit-metabolic",
    className: "HIIT: METABOLIC BURN",
    classDate: "OCT 16",
    startTime: "05:00 PM",
    trainerName: "Coach Sarah",
    status: "CONFIRMED",
  },
];

export const mockBillingHistory: BillingHistoryItem[] = [
  {
    id: "bl-1",
    description: "Monthly Pro Membership",
    date: "Sep 28, 2024",
    amount: 180.0,
  },
  {
    id: "bl-2",
    description: "Personal Training (x4)",
    date: "Sep 15, 2024",
    amount: 450.0,
  },
  {
    id: "bl-3",
    description: "Monthly Pro Membership",
    date: "Aug 28, 2024",
    amount: 180.0,
  },
];
