import { MembershipPlan, Trainer, GymClass, Testimonial, BlogPost, GalleryItem, ClassBooking, BillingHistoryItem } from "@/types";

export const membershipPlans: MembershipPlan[] = [
  {
    id: "plan-starter",
    name: "STARTER",
    slug: "starter",
    monthlyPrice: 999,
    annualPrice: 799,
    category: "BASIC ACCESS",
    isPopular: false,
    features: [
      "Access to open gym and barbell platforms",
      "Full locker room and shower access",
      "Complimentary sweat towel service",
      "No contract, cancel anytime",
    ],
  },
  {
    id: "plan-pro",
    name: "PRO",
    slug: "pro",
    monthlyPrice: 1799,
    annualPrice: 1439,
    category: "FULL EXPERIENCE",
    isPopular: true,
    features: [
      "All Starter tier access",
      "Unlimited access to group classes",
      "Infrared sauna and cold plunge access",
      "2 guest day-passes per month",
    ],
  },
  {
    id: "plan-elite",
    name: "ELITE",
    slug: "elite",
    monthlyPrice: 2999,
    annualPrice: 2399,
    category: "VIP STATUS",
    isPopular: false,
    features: [
      "All Pro tier access",
      "Private day locker and laundry service",
      "1-on-1 monthly training assessment",
      "10% discount on guest passes and retail",
    ],
  },
];

export const trainers: Trainer[] = [
  {
    id: "trainer-marcus",
    name: "MARCUS VANCE",
    slug: "marcus-vance",
    specialization: ["STRENGTH & CONDITIONING"],
    bio: "Strength coach with 12+ years of experience training powerlifters and recreational athletes.",
    longBio: "Marcus specializes in building strength and structural resilience. With a Master's in Exercise Physiology and 12 years of hands-on experience, he combines structured barbell training with recovery protocols that help lifters stay injury-free and consistent. He has coached competitive powerlifters and individuals looking to rebuild their strength baseline.",
    experience: 12,
    certifications: [
      "NSCA Certified Strength & Conditioning Specialist",
      "NASM Performance Enhancement Specialist",
      "Precision Nutrition L2",
      "Westside Barbell Certified",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7PV96otBPskyWgLMrT8T-tZenQxysbG9VGdRfA0rEFrzDR-YL4L4iQSewl2EU9nDzIzWFJUBhTufjoXCLO--uhrq2dVPcNVqxifmaGUmfyU33a0lsM_rtgoHcywE_YUR1DAuo8sn4gkB6cEHsDV7SNMjC47Pc20vutONObM1VXXhohTXVR7PP0ks-o-t81LRgarqVbSqj8KNN1X0y6rMjtmCua4djKXxMSNdk8g06v4onVqtxnlOsD1ypBTAotdsFPzkP8sbZk_FG",
    instagramUrl: "https://instagram.com/marcusvance",
    rating: 4.9,
    isFeatured: true,
    quote: "Consistency and structured progression are the keys to long-term strength.",
    schedule: [
      { days: "MON-WED", hours: "06:00 - 12:00" },
      { days: "THU-FRI", hours: "14:00 - 20:00" },
      { days: "SATURDAY", hours: "08:00 - 14:00" },
      { days: "SUNDAY", hours: "CLOSED" },
    ],
  },
  {
    id: "trainer-elara",
    name: "ELARA JENKINS",
    slug: "elara-jenkins",
    specialization: ["BODY COMPOSITION & STRENGTH"],
    bio: "Specialist in body composition, hypertrophy, and sustainable nutrition coaching.",
    longBio: "Elara focuses on helping members build muscle, lose body fat, and establish healthy nutritional habits. She uses evidence-based hypertrophy training combined with structured, non-restrictive diet plans to make body transformations sustainable for busy professionals.",
    experience: 9,
    certifications: [
      "IFBB Pro Card Holder",
      "ACE Certified Personal Trainer",
      "FMS Level 2 Specialist",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEkr3yICD7yBDvTNxGklbCum24uXa-Ur1sFqkn2LCsEpWHtBF2971eLTece4mKZgCQkzPk7sscPhJgecYOJcMJsDRbF3nZR_fQNWHZbtWqS6ILWv-KU7e3ojTwB51myzoWxe7etSavDMznzgpMuNWCBzGMgVc-peHgz-870B4bww2l6vlDvJcVOJXHH0OgMVBWyFJeh5KNLDkjpn0czoSh6LuWpjOaOpOvo-P2p6ZH3Wb0N6H2bmLROIybWGjNJoGKY2sC7aj9MKur",
    instagramUrl: "https://instagram.com/elarajenkins",
    rating: 4.8,
  },
  {
    id: "trainer-david",
    name: "DR. DAVID CHOW",
    slug: "david-chow",
    specialization: ["EXPLOSIVE POWER & ATHLETICISM"],
    bio: "Ph.D. in Biomechanics specializing in athletic power, speed, and injury prevention.",
    longBio: "David brings a scientific approach to athletic development. Holding a Ph.D. in Biomechanics, he works with athletes and active individuals to build explosive power, improve movement mechanics, and design conditioning programs that transfer directly to sports or daily life.",
    experience: 15,
    certifications: [
      "PhD in Sports Biomechanics",
      "CSCS *D (Distinction)",
      "USA Weightlifting Coach L2",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDu90Ol4rXkzvvGsvVmOVNnN_AQ-wIVfXsTv_J3Yk9Bctpjxyy8ucNSOuxDyvRCwuh1QmNnBxsAcUFVURw7d0NcwZtCciflIeYz67ijcdk2i2A5Tht0Tp4AeQ30JiHHLacH3JGn7Pc7XdIRnCyszsvEX3jgPcuhp-oBK8GRMylrtrxoaQXy01u4zNYxiyURxDz074jhNQGLhMqXbnII4WuIDBbuE86jbHETNyFFMSzqRUDoD7jiiyQv4tUBawk6b1ZVCZkUdQ_gh8Cr",
    instagramUrl: "https://instagram.com/drdavidchow",
    rating: 5.0,
  },
  {
    id: "trainer-sarah",
    name: "SARAH NIGHTINGALE",
    slug: "sarah-nightingale",
    specialization: ["MOBILITY & RECOVERY"],
    bio: "Specialist in active recovery, joint mobility, and corrective exercise.",
    longBio: "Sarah helps lifters improve joint mobility, correct postural imbalances, and recover effectively from high-volume training. Her programming combines active mobility drills, core stability work, and restorative movements to keep you moving pain-free.",
    experience: 8,
    certifications: [
      "Registered Yoga Teacher (RYT-500)",
      "Corrective Exercise Specialist (CES)",
      "Dynamic Neuromuscular Stabilization (DNS) Practitioner",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC5X4OLeaz9WDNeMCT4F8e4XDKD2T_DwB8ryVowkJXOoeFBMtGDFSCQxaw1Ep2ilwAAHoaVIVhYcq8-8CpdzUy49ySiN2sSBaOuFt7hVL1KKluMrgn6XSqIoBz-Hhs0yuHdjxD37yX8UeUXF5ZzY8VsdvSxRxiok8bm8Xo0NMChOH4ramHdGb8AP6C80bB-Kc4ylvH-ArH3cNsEeevhIsix21j8WTL1dUH9Aq3wmIsvvGVwW0Rad6MExHawyLaaTv85v9hgvXOg-WKe",
    rating: 4.7,
  },
  {
    id: "trainer-jaxson",
    name: "JAXSON REED",
    slug: "jaxson-reed",
    specialization: ["FUNCTIONAL FITNESS & CONDITIONING"],
    bio: "Specializing in high-intensity conditioning and functional strength training.",
    longBio: "Jaxson specializes in functional strength and high-intensity conditioning. He blends carry patterns, kettlebell work, and energy-system training to build work capacity, endurance, and practical strength.",
    experience: 7,
    certifications: [
      "CrossFit Level 3 Trainer",
      "NASM Performance Enhancement Specialist",
      "IKFF Kettlebell Master Trainer",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA-ESeVWwa3kYWi58hnSPxbgKBO_ShArKZHkxjsDUZqP5LraPnvj46IciA3HMCA5T1jtwNgqF7Dz6K76UKr-fFehGRSlBWOTNWLW9KbT8aNqKrnj1tJbSMbTPSC31e0ZvbDlDOdwgbgZaIJZIxip_60DP-mSl4fvOtaWGe3Kzn2NB-OAqtRqnjQUkxO2EthRpnE8t8yfOSIKZuKO9RhkFl6BzBxrTB_xLaDiH-ZGsYlN4dotZ-1cJh16eE9GIYClf7DnOiJZmzEvguV",
    rating: 4.8,
  },
  {
    id: "trainer-sofia",
    name: "SOFIA VALENTINE",
    slug: "sofia-valentine",
    specialization: ["STRENGTH & FITNESS FOUNDER"],
    bio: "Founder of IronForge, with 15 years of experience in strength coaching and gym operations.",
    longBio: "Sofia founded IronForge to provide a gym environment focused on serious lifting and experienced coaching. Over the past 15 years, she has trained clients ranging from competitive athletes to people starting their fitness journey, focusing on teaching proper lifting mechanics and progressive training.",
    experience: 15,
    certifications: [
      "Master Trainer (EHFA)",
      "BSc in Exercise Science",
      "Poliquin Strength Coach L3",
    ],
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBIr9Rw2wtCwtDT9p9INkogrClVrSgzBAygac1zCu-zCrmUZbvMDByRkbrWGaVwy_UsHwySOq03MtU8AnuGlzwrQCTwWhj9_eXEBHB71irrsGwNauTngJW7hwFX6R4p3ITpn6SQOfZueYum_9SeTWiBo5al1J8eFp05fGuVElGoWGNXIlDLMvCvQupWt-K96v0pDP-E1vFfxgDoWPqbC_zdlE5k0CuDg1NeZOPa-CPmArDDBqJo1UHpgE4dUIA2OENR6DFwYugfsQ4W",
    rating: 5.0,
    isFeatured: true,
  },
];

export const gymClasses: GymClass[] = [
  {
    id: "class-crossfit",
    name: "METABOLIC CONDITIONING",
    slug: "elite-crossfit-amrap",
    description: "A high-intensity conditioning class combining functional movement, kettlebells, and cardio machines to improve your work capacity.",
    type: "CROSSFIT",
    trainerId: "trainer-jaxson",
    trainerName: "Coach Jaxson",
    dayOfWeek: 1, // Mon
    startTime: "07:00",
    duration: 60,
    capacity: 20,
    slotsLeft: 5,
    isFeatured: true,
  },
  {
    id: "class-hiit-mon",
    name: "HIIT & CARDIO",
    slug: "power-hiit",
    description: "Interval-based conditioning sessions designed to improve your cardiovascular endurance using rowers, bikes, and bodyweight movements.",
    type: "HIIT",
    trainerId: "trainer-sarah",
    trainerName: "Coach Sarah",
    dayOfWeek: 1, // Mon
    startTime: "06:00",
    duration: 45,
    capacity: 15,
    slotsLeft: 4,
  },
  {
    id: "class-yoga-mon",
    name: "MOBILITY & FLOW YOGA",
    slug: "flow-yoga",
    description: "A Vinyasa yoga class focused on increasing joint range of motion, improving balance, and supporting post-workout recovery.",
    type: "YOGA",
    trainerId: "trainer-sarah",
    trainerName: "Coach Sarah",
    dayOfWeek: 1, // Mon
    startTime: "08:30",
    duration: 60,
    capacity: 15,
    slotsLeft: 0,
  },
  {
    id: "class-strength-mon",
    name: "STRENGTH LAB",
    slug: "strength-lab",
    description: "A coach-led class focusing on core barbell lifts—squats, deadlifts, and presses—to teach proper technique and build strength.",
    type: "STRENGTH",
    trainerId: "trainer-marcus",
    trainerName: "Coach Marcus",
    dayOfWeek: 1, // Mon
    startTime: "17:00",
    duration: 60,
    capacity: 12,
    slotsLeft: 12,
  },
  {
    id: "class-core-tue",
    name: "CORE & STABILITY",
    slug: "core-blast",
    description: "Focuses on building abdominal strength, lower back stability, and rotational control through structured bodyweight and resistance exercises.",
    type: "STRENGTH",
    trainerId: "trainer-elara",
    trainerName: "Coach Elara",
    dayOfWeek: 2, // Tue
    startTime: "07:00",
    duration: 45,
    capacity: 15,
    slotsLeft: 2,
  },
  {
    id: "class-boxing-wed",
    name: "IRON BOXING",
    slug: "iron-boxing",
    description: "A cardio-boxing workout focused on heavy bag drills, basic footwork, and punch combinations.",
    type: "BOXING",
    trainerId: "trainer-david",
    trainerName: "Coach David",
    dayOfWeek: 3, // Wed
    startTime: "06:00",
    duration: 60,
    capacity: 10,
    slotsLeft: 0,
  },
  {
    id: "class-yoga-thu",
    name: "RECOVERY & STRETCH",
    slug: "zen-flow",
    description: "A low-intensity stretching and mobility class designed to reduce muscle soreness and improve flexibility.",
    type: "YOGA",
    trainerId: "trainer-sarah",
    trainerName: "Coach Sarah",
    dayOfWeek: 4, // Thu
    startTime: "18:30",
    duration: 60,
    capacity: 15,
    slotsLeft: 8,
  },
  {
    id: "class-amrap-fri",
    name: "CONDITIONING CIRCUITS",
    slug: "amrap-elite",
    description: "Time-based circuit training that mixes bodyweight exercises and free weights to build muscular endurance.",
    type: "CROSSFIT",
    trainerId: "trainer-jaxson",
    trainerName: "Coach Jaxson",
    dayOfWeek: 5, // Fri
    startTime: "06:00",
    duration: 60,
    capacity: 20,
    slotsLeft: 5,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Alexander Vance",
    role: "Member since 2023",
    rating: 5,
    quote: "IronForge has the best lifting equipment in the city. The atmosphere is focused, and having access to saunas and cold plunges makes recovery easy.",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC5X4OLeaz9WDNeMCT4F8e4XDKD2T_DwB8ryVowkJXOoeFBMtGDFSCQxaw1Ep2ilwAAHoaVIVhYcq8-8CpdzUy49ySiN2sSBaOuFt7hVL1KKluMrgn6XSqIoBz-Hhs0yuHdjxD37yX8UeUXF5ZzY8VsdvSxRxiok8bm8Xo0NMChOH4ramHdGb8AP6C80bB-Kc4ylvH-ArH3cNsEeevhIsix21j8WTL1dUH9Aq3wmIsvvGVwW0Rad6MExHawyLaaTv85v9hgvXOg-WKe",
  },
  {
    id: "test-2",
    name: "Sarah Chen",
    role: "Active Member",
    rating: 5,
    quote: "The trainers here are highly knowledgeable and helped me structure a lifting program that supports my running. The facility is always clean and well-maintained.",
    avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBIr9Rw2wtCwtDT9p9INkogrClVrSgzBAygac1zCu-zCrmUZbvMDByRkbrWGaVwy_UsHwySOq03MtU8AnuGlzwrQCTwWhj9_eXEBHB71irrsGwNauTngJW7hwFX6R4p3ITpn6SQOfZueYum_9SeTWiBo5al1J8eFp05fGuVElGoWGNXIlDLMvCvQupWt-K96v0pDP-E1vFfxgDoWPqbC_zdlE5k0CuDg1NeZOPa-CPmArDDBqJo1UHpgE4dUIA2OENR6DFwYugfsQ4W",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "blog-1",
    title: "THE BIOMECHANICS OF THE compound Deadlift",
    slug: "biomechanics-deadlift",
    excerpt: "Breaking down joint load, neural fatigue, and muscular coordination for maximum structural output.",
    category: "TRAINING",
    readTime: "6 min read",
    publishedAt: "OCT 05, 2024",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7PV96otBPskyWgLMrT8T-tZenQxysbG9VGdRfA0rEFrzDR-YL4L4iQSewl2EU9nDzIzWFJUBhTufjoXCLO--uhrq2dVPcNVqxifmaGUmfyU33a0lsM_rtgoHcywE_YUR1DAuo8sn4gkB6cEHsDV7SNMjC47Pc20vutONObM1VXXhohTXVR7PP0ks-o-t81LRgarqVbSqj8KNN1X0y6rMjtmCua4djKXxMSNdk8g06v4onVqtxnlOsD1ypBTAotdsFPzkP8sbZk_FG",
    author: {
      name: "Marcus Vance",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsjiYXVk4_c4TMuJm4SffWthpskERIzWG_fu4gy5N_8pBSeYE27wQ8Pii1Vv3gkhJnBxguKyie5t5c1yvxUNFP7PyHYQPl4QP9aCHhVHDYlajcwaWItcHe1DJx1jBQyRPKu8nHMw2IXKX-aHwb1BhSs5i9Oh28JJKXtS8M91INR660_331PELqZIdGr1GwKRMw3f_Vrzjeb9R8huS38Lt8CEqgkrCLz9oZWQBSFxMOeHVAelWPy1Aaik6QmJjkxHXKZd0Cy9ZY9Vns",
    },
  },
  {
    id: "blog-2",
    title: "METABOLIC ADAPTATION IN CALORIC deficit",
    slug: "metabolic-adaptation-deficit",
    excerpt: "How thyroid activity and energy efficiency adjust during fat loss blocks—and how to offset stagnation.",
    category: "NUTRITION",
    readTime: "8 min read",
    publishedAt: "SEP 28, 2024",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxKZYzKOKQ9iNOCI79TLv6OdmgAWT7QeNNMsYJoI3ciV1UJunF1ivi2pfYlinXbtEKTOPRmwnCAFFQTUQEGA4lHfG4-qDvYAy787Lu-C5EHBCXqpto2b8zyF-D2TcFO-4t98y_HzeUGLriKoYTxqky_XD9ei5KbhbZybpMy3UxuXfSv9jP1NAhpBi3mn_fMcRvL0nWVGgtsdXnf27DLwOMLnZ0nX4CrFL5i97qaEuJqq07TNhU9apd83LSyM4smA_BhTG1ctW3Jtz5",
    author: {
      name: "Elara Jenkins",
      imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEkr3yICD7yBDvTNxGklbCum24uXa-Ur1sFqkn2LCsEpWHtBF2971eLTece4mKZgCQkzPk7sscPhJgecYOJcMJsDRbF3nZR_fQNWHZbtWqS6ILWv-KU7e3ojTwB51myzoWxe7etSavDMznzgpMuNWCBzGMgVc-peHgz-870B4bww2l6vlDvJcVOJXHH0OgMVBWyFJeh5KNLDkjpn0czoSh6LuWpjOaOpOvo-P2p6ZH3Wb0N6H2bmLROIybWGjNJoGKY2sC7aj9MKur",
    },
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Strength Training Facilities",
    category: "EQUIPMENT",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7PV96otBPskyWgLMrT8T-tZenQxysbG9VGdRfA0rEFrzDR-YL4L4iQSewl2EU9nDzIzWFJUBhTufjoXCLO--uhrq2dVPcNVqxifmaGUmfyU33a0lsM_rtgoHcywE_YUR1DAuo8sn4gkB6cEHsDV7SNMjC47Pc20vutONObM1VXXhohTXVR7PP0ks-o-t81LRgarqVbSqj8KNN1X0y6rMjtmCua4djKXxMSNdk8g06v4onVqtxnlOsD1ypBTAotdsFPzkP8sbZk_FG",
    alt: "Our primary strength training area, equipped with Hammer Strength racks and competition barbells.",
  },
  {
    id: "gal-2",
    title: "Conditioning & Functional Area",
    category: "CLASSES",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8LuNheH21q5pKpQlxwaEvcDD24HmVRtGmoO6PSMWL8YMsJY_SHCvrxZun65RH63L4Mmq03gs4-B0mVv72qtxTjel-JmcpRnZT1CWjhqTC83u6i5ZjOHeYThZdM9gEkgfEqvSUr-5PZP3F3KBjiFEVdAHG0YKcfJufxgCWlmNemRpU_PpU5KPf0pS3Ew7JqqZwY0x2MeOrWL_b22uO0-4TJrLxFi7qIkXuM2QXYVV0O8jILrgKWdQ6cGBqdwTEa16XGES9-9gpLl_L",
    alt: "Members training in our dedicated functional fitness space, configured for kettlebells, sleds, and high-intensity work.",
  },
];

export const mockDashboardBookings: ClassBooking[] = [
  {
    id: "bk-1",
    classId: "class-strength-foundations",
    className: "POWER LIFTING: FOUNDATIONS",
    classDate: "OCT 14",
    startTime: "06:30 AM",
    trainerName: "Coach Marcus",
    status: "CONFIRMED",
  },
  {
    id: "bk-2",
    classId: "class-hiit-metabolic",
    className: "HIIT: METABOLIC BURN",
    classDate: "OCT 16",
    startTime: "05:00 PM",
    trainerName: "Coach Sarah",
    status: "CONFIRMED",
  },
];

export const mockBillingHistory: BillingHistoryItem[] = [
  {
    id: "bl-1",
    description: "Monthly Pro Membership",
    date: "Sep 28, 2024",
    amount: 180.0,
  },
  {
    id: "bl-2",
    description: "Personal Training (x4)",
    date: "Sep 15, 2024",
    amount: 450.0,
  },
  {
    id: "bl-3",
    description: "Monthly Pro Membership",
    date: "Aug 28, 2024",
    amount: 180.0,
  },
];
